# Generated by Django 4.2.5 on 2023-10-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remaining_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
